export const APP_GET_URL_ASYNC_REQUEST = "APP_GET_URL_ASYNC_REQUEST";
export const APP_GET_URL_ASYNC_SUCCESS = "APP_GET_URL_ASYNC_SUCCESS";
export const APP_GET_URL_ASYNC_FAIL = "APP_GET_URL_ASYNC_FAIL";
