export const GET_STREAM_ROOM_LIST_REQUEST = "GET_STREAM_ROOM_LIST_REQUEST";
export const GET_STREAM_ROOM_LIST_SUCCESS = "GET_STREAM_ROOM_LIST_SUCCESS";
export const GET_STREAM_ROOM_LIST_FAIL = "GET_STREAM_ROOM_LIST_FAIL";
